apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netshoot
  namespace: default
  labels:
    app: netshoot
spec:
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name: netshoot
        image: "docker.io/nicolaka/netshoot:v0.12"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        command: ["/bin/bash"]
        args: ["-c", "while true; do ping localhost; sleep 60;done"]
